#!/bin/bash
cd /home/pi/pits/tracker
./send_aprs &
echo none | sudo tee /sys/class/leds/led0/trigger
echo 1 | sudo tee /sys/class/leds/led0/brightness
sudo ./camera &
python savesensor.py &
#python3 astro_led.py &
#python3 webstuff.py
while :
do

    python=`ps aux | grep -i "python " | grep -v "grep" | wc -l`
    if [ $python -ge 1 ]
       then
            echo "python is running"
       else
            echo "python is not running, restarting"
            python /home/pi/pits/tracker/savesensor.py  > /dev/null &
    fi
    
	sudo ./tracker
	sleep 5
done

