#!/bin/bash
cd /home/pi/lora-gateway

while :
do

    python=`ps aux | grep -i "python " | grep -v "grep" | wc -l`
    if [ $python -ge 1 ]
       then
            echo "python is running"
       else
            echo "python is not running, restarting"
            python /home/pi/pits/tracker/savesensor.py  > /dev/null &
    fi

    sleep 30
done
